trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Replacing the Restore task with DotNetCoreCLI
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.sln'  # Restore all solutions in the repo

  - task: DotNetCoreCLI@2  # Build step
    inputs:
      command: 'build'
      projects: '**/*.sln'
      arguments: '--configuration Release'

  - task: DotNetCoreCLI@2  # Test step
    inputs:
      command: 'test'
      projects: '**/*.Tests/*.csproj'  # Use appropriate test project path
      arguments: '--configuration Release'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
